ByteXecomWeb/Areas/Administrator/Controllers/ProductBrandController.cs
using ByteXecom.DataAccess;
using ByteXecom.DataAccess.Repository.IRepository;
using ByteXecom.Models;
using Microsoft.AspNetCore.Mvc;

namespace ByteXecomWeb.Controllers
{
    [Area("Administrator")]
    public class ProductBrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProductBrandController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IList<ProductBrand> objList = _unitOfWork.ProductBrand.GetAll();
            return View(objList);
        }

        //GET Action
        public IActionResult Create()
        {
            return View();
        }

        //POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductBrand obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.ProductBrand.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Product Brand Created Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET Action
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            //var productCategoryReturned = _db.ProductCategories.Find(id);
            var productBrandFromDbFirst = _unitOfWork.ProductBrand.GetFirstOrDefault(u => u.Id == id);
            if(productBrandFromDbFirst == null)
            {
                return NotFound();
            }
            return View(productBrandFromDbFirst);
        }

        //POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductBrand obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.ProductBrand.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Product Brand Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET Action
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var productCategoryReturned = _db.ProductCategories.Find(id);
            var productBrandFromDbFirst = _unitOfWork.ProductBrand.GetFirstOrDefault(u => u.Id == id);
            if (productBrandFromDbFirst == null)
            {
                return NotFound();
            }
            return View(productBrandFromDbFirst);
        }

        //POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var productBrandFromDbFirst = _unitOfWork.ProductBrand.GetFirstOrDefault(u => u.Id == id);
            if (productBrandFromDbFirst == null)
            {
                return NotFound();
            }
            _unitOfWork.ProductBrand.Remove(productBrandFromDbFirst);
            _unitOfWork.Save();
            TempData["success"] = "Product Brand Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

ByteXecomWeb/Areas/Administrator/Controllers/ProductCategoryController.cs
using ByteXecom.DataAccess;
using ByteXecom.DataAccess.Repository.IRepository;
using ByteXecom.Models;
using Microsoft.AspNetCore.Mvc;

namespace ByteXecomWeb.Controllers
{
    [Area("Administrator")]
    public class ProductCategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProductCategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IList<ProductCategory> objCategoryList = _unitOfWork.ProductCategory.GetAll();
            return View(objCategoryList);
        }

        //GET Action
        public IActionResult Create()
        {
            return View();
        }

        //POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductCategory obj)
        {
            
            if (ModelState.IsValid)
            {
                _unitOfWork.ProductCategory.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Product Category Created Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET Action
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            //var productCategoryReturned = _db.ProductCategories.Find(id);
            var productCategoryFromDbFirst = _unitOfWork.ProductCategory.GetFirstOrDefault(u => u.Id == id);
            if(productCategoryFromDbFirst == null)
            {
                return NotFound();
            }
            return View(productCategoryFromDbFirst);
        }

        //POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProductCategory obj)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.ProductCategory.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Product Category Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET Action
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var productCategoryReturned = _db.ProductCategories.Find(id);
            var productCategoryFromDbFirst = _unitOfWork.ProductCategory.GetFirstOrDefault(u => u.Id == id);
            if (productCategoryFromDbFirst == null)
            {
                return NotFound();
            }
            return View(productCategoryFromDbFirst);
        }

        //POST Action Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var productCategoryFromDbFirst = _unitOfWork.ProductCategory.GetFirstOrDefault(u => u.Id == id);
            if (productCategoryFromDbFirst == null)
            {
                return NotFound();
            }
            _unitOfWork.ProductCategory.Remove(productCategoryFromDbFirst);
            _unitOfWork.Save();
            TempData["success"] = "Product Category Deleted Successfully";
            return RedirectToAction("Index");
        }
    }
}

ByteXecomWeb/Areas/Customer/Controllers/HomeController.cs
using ByteXecom.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ByteXecomWeb.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ByteXecomWeb/Areas/Administrator/Views/ProductBrand/Create.cshtml
@model ProductBrand

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Create New Product Brand</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-1 text-end">
        <a asp-controller="ProductBrand" asp-action="Index" class="btn btn-primary" style="width:150px;">Back</a>
        <button type="submit" class="btn btn-success" style="width:150px;"> Create </button>
        </div>
        
    </div>
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ByteXecomWeb/Areas/Administrator/Views/ProductBrand/Delete.cshtml
@model ProductBrand

<form method="post" asp-action="DeletePOST">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Delete Product Brand</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
            
        </div>
        <div class="mb-1 text-end">
        <a asp-controller="ProductBrand" asp-action="Index" class="btn btn-primary" style="width:150px;">Back</a>
        <button type="submit" class="btn btn-danger" style="width:150px;"> Delete </button>
        </div>
        
    </div>
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ByteXecomWeb/Areas/Administrator/Views/ProductBrand/Edit.cshtml
@model ProductBrand

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Update Product Brand</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-1 text-end">
        <a asp-controller="ProductBrand" asp-action="Index" class="btn btn-primary" style="width:150px;">Back</a>
        <button type="submit" class="btn btn-success" style="width:150px;"> Update </button>
        </div>
        
    </div>
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ByteXecomWeb/Areas/Administrator/Views/ProductBrand/Index.cshtml
@model IList<ProductBrand>
@{
    ViewData["Title"] = "Index";
}




<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h1>All Product Brands</h1>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ProductBrand" asp-action="Create" class="btn btn-success">
              <i class="bi bi-file-earmark-plus-fill"></i> Add Product Brand 
            </a>
            <br />
            <br />
        </div>
    </div>
</div>


<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td width="50%">
                    @item.Name
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="ProductBrand" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="ProductBrand" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mx-2"> <i class="bi bi-trash3-fill"></i> Delete</a>
                    </div>
                </td>
                <td>
                    <div class="w-50 btn-group" role="group">
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

ByteXecomWeb/Areas/Administrator/Views/ProductCategory/Create.cshtml
@model ProductCategory

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Create New Product Category</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-1 text-end">
        <a asp-controller="ProductCategory" asp-action="Index" class="btn btn-primary" style="width:150px;">Back</a>
        <button type="submit" class="btn btn-success" style="width:150px;"> Create </button>
        </div>
        
    </div>
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ByteXecomWeb/Areas/Administrator/Views/ProductCategory/Delete.cshtml
@model ProductCategory

<form method="post" asp-action="DeletePOST">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Delete Product Category</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
            
        </div>
        <div class="mb-1 text-end">
        <a asp-controller="ProductCategory" asp-action="Index" class="btn btn-primary" style="width:150px;">Back</a>
        <button type="submit" class="btn btn-danger" style="width:150px;"> Delete </button>
        </div>
        
    </div>
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ByteXecomWeb/Areas/Administrator/Views/ProductCategory/Edit.cshtml
@model ProductCategory

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Update Product Category</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-1 text-end">
        <a asp-controller="ProductCategory" asp-action="Index" class="btn btn-primary" style="width:150px;">Back</a>
        <button type="submit" class="btn btn-success" style="width:150px;"> Update </button>
        </div>
        
    </div>
</form>
@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ByteXecomWeb/Areas/Administrator/Views/ProductCategory/Index.cshtml
@model IList<ProductCategory>
@{
    ViewData["Title"] = "Index";
}




<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h1>All Product Categories</h1>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="ProductCategory" asp-action="Create" class="btn btn-success">
              <i class="bi bi-file-earmark-plus-fill"></i> Add Product Category 
            </a>
            <br />
            <br />
        </div>
    </div>
</div>


<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td width="50%">
                    @item.Name
                </td>
                <td>
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="ProductCategory" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                        <a asp-controller="ProductCategory" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mx-2"> <i class="bi bi-trash3-fill"></i> Delete</a>
                    </div>
                </td>
                <td>
                    <div class="w-50 btn-group" role="group">
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

ByteXecomWeb/Areas/Customer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome ByteXpress Team!</h1>
    <p>This is the ByteXecom project.</p>
</div>

ByteXecomWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ByteXecomWeb</title>
    <link rel="stylesheet" href="~/css/customeTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ByteXecomWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
             <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
             <a class="nav-link text-light" asp-area="Administrator" asp-controller="ProductCategory" asp-action="Index">Product Categories</a>
        </li>
         <li class="nav-item">
             <a class="nav-link text-light" asp-area="Administrator" asp-controller="ProductBrand" asp-action="Index">Product Brands</a>
        </li>
       
       @* <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>*@
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer id="footer" class="border-top pt-3">
        <div class="container">
            &copy; 2022 - ByteXecomWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ByteXecomWeb/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}